#!/bin/sh
#ローカル以外からのSSHでメールしてくれるやつ
#多分必要: s-nail ssmtp
#ssmtpは要設定

Clear4='192'
Clear6='fe80'
From4=${SSH_CLIENT:0:3}
From6=${SSH_CLIENT:0:4}
if [ "$Clear4" != "$From4" -a "$Clear6" != "$From6" ]; then
	echo -e "`date`\n\"$USER\" has logged on from $SSH_CLIENT" | mailx -s "SSH LOGIN ALERT" inux.0x27@gmail.com
fi

