#!/bin/bash
V4_LOCAL=192.168
V6_LOCAL=fe80::
V6_GROBAL=2001:a005:c33a:0:
if [[ "$SSH_CLIENT" =~ $V6_GROBAL ]];then
	echo "From Local"
	exit 0
fi
if [[ "$SSH_CLIENT" =~ $V6_LOCAL ]];then
	echo "From Local"
	exit 0
fi
if [[ "$SSH_CLIENT" =~ $V4_LOCAL ]];then
	echo "From Local"
	exit 0
fi

echo -e "`date`\n\"$USER\" has logged on from $SSH_CLIENT" | mailx -s "SSH LOGIN ALERT" inux.0x27@gmail.com

