#!/bin/bash
V4_L=192.168
V6_L=fe80::
V6_G=2001:a005:c33a:0:
if [[ "$SSH_CLIENT" =~ $V6_G ]] || [[ "$SSH_CLIENT" =~ $V6_L ]] || \
	[[ "$SSH_CLIENT" =~ $V4_L ]]; then
#	echo "From Local"
	exit 0
fi

echo -e "`date`\n\"$USER\" has logged on from $SSH_CLIENT" | mailx -s "SSH LOGIN ALERT" inux.0x27@gmail.com

### SSH ALERT for LINE
# echo -e "$USER@$HOST にログイン\nDate: `date`\nFrom: $SSH_CLIENT" | $CMD
#

