#!/bin/bash
tex=$1
argv=$#
if [ $argv = 0 ] ; then
	echo "texファイルを指定してください"
	exit 1
fi
name=${tex//.tex/}
dvi=${tex//tex/dvi}
platex ${tex}
platex ${tex}
dvipdfmx ${dvi}

rm ${name}.log ${dvi} ${name}.aux
