#!/bin/sh
cdpath=$(cd $(dirname $0); pwd)
vimrc=$cdpath/.vimrc
zshrc=$cdpath/.zshrc
fonts=$cdpath/.fonts.conf

# vimrc
if [ ! -e ~/.vimrc ]; then
	ln -s $vimrc ~/
fi

# zshrc
if [ ! -e ~/.zshrc ]; then
	ln -s $zshrc ~/
	source ~/.zshrc
fi

# bin
if [ ! -e ~/bin ]; then
	mkdir ~/bin
fi
if [ ! -e ~/bin/makepdf ]; then
	ln -s $cdpath/makepdf ~/bin 
fi

# vim bundle install
if [ ! -e ~/.vim/bundle ]; then
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
fi

