#!/bin/sh
home=~/
cdpath=$(cd $(dirname $0); pwd)
vimrc=$cdpath/.vimrc
zshrc=$cdpath/.zshrc
fonts=$cdpath/.fonts.conf
ln -s $vimrc $home
ln -s $zshrc $home
ln -s $cdpath/makepdf $home/bin
cp $fonts $home
echo "Complete"
