[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

# Theme
[[plugins]]
repo = 'tomasr/molokai'

# git diff on vim
#[[plugins]]
#repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

# status bar theme
#[[plugins]]
#repo = 'itchyny/lightline.vim'

# スペース見える化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ステータスライン
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# アイコンフォント
[[plugins]]
repo = 'ryanoasis/vim-devicons'

