# 自動括弧閉じ
[[plugins]]
repo = "kana/vim-smartinput"
on_i = 1

# カッコをうまくやる
[[plugins]]
repo = "tpope/vim-surround"
on_i = 1

# テーブル整形
[[plugins]]
repo = "dhruvasagar/vim-table-mode"
on_ft = ["markdown"]

# Syntax
# C++
[[plugins]]
repo = "vim-jp/cpp-vim"
on_ft = ["cpp"]

[[plugins]]
repo = "octol/vim-cpp-enhanced-highlight"
on_ft = ["cpp"]

[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = ["rust"]

#[[plugins]]
#repo = "racer-rust/vim-racer"
#on_ft = ["rust"]

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]]
repo = "udalov/kotlin-vim"
on_ft = ["kotlin"]

[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]


[[plugins]]
repo = "pangloss/vim-javascript"
on_ft = ["javascript", "typescript", "typescriptreact"]
