#!/bin/zsh
set -Ceu
keep=8
date=`date +%Y%m%d`
root='/mnt/array0'
backup=('Documents' 'Git' 'Music' 'Photo' 'Rec' 'Recorded')
snapshot='Snapshot'

if [ ! -e $root/$snapshot/$date ]; then
    mkdir -v $root/$snapshot/$date
    for i in $backup; do
        btrfs subvolume snapshot $root/$i $root/$snapshot/$date/$i
    done
fi

for file in `find $root/$snapshot -maxdepth 1 -mtime +$keep`; do
    for i in $backup; do
        btrfs subvolume delete $file/$i
    done
    rmdir -v $file
done

