#!/bin/zsh
set -Ceu
keep=7
date=`date +%Y%m%d`
root='/mnt/array0'
backup=('Documents' 'Git' 'Music' 'Photos' 'Rec' 'Recorded')
snapshot='Snapshot'

if [ ! -e $root/$snapshot/$date ]; then
    mkdir -v $root/$snapshot/$date
    for i in $backup; do
        btrfs subvolume snapshot $root/$i $root/$snapshot/$date/$i
    done
fi

for file in `find $root/$snapshot -maxdepth 1 -mindepth 1 -mtime $keep`; do
    for sub in `find $file -maxdepth 1 -mindepth 1`; do
        btrfs subvolume delete --verbose $sub
    done
    rmdir -v $file
done

