#!/bin/sh
ffmpeg=$HOME/bin/ffmpeg_
flag=true
IFS=$'\n'
function encoding () {
	${ffmpeg} -n -i "$1" -vcodec libx265 -vpre x265\
	-filter:v yadif=1:-1:0 -acodec libfdk_aac "${1%ts}mp4"
}
for file in `find . -maxdepth 1 -name '*.ts'`; do
	if [ ! -e "${file%ts}mp4" ]; then
		encoding $file
		flag=false
	else
		flag=true
	fi
done

if [[ $1 != true ]]; then
	$0 $flag
fi

