#!/bin/zsh
set -Ceu
dir=WD30EFRX
uroot=/tmp/`whoami`
full_mount=("/mnt/WD30EFRX" "/mnt/array0")
mount="/mnt/array0"

if [ $# = 0 ]; then
    if [ `hostname` = "arcticfox" ]; then
        for i in "${full_mount[@]}"; do
            fusermount -uz $i
        done
    else
        fusermount -uz $mount
    fi
else
    if [ $1 = "all" ]; then
        sshfs-umount
        sshfs-umount arc
    fi

    if [ $1 = "arc" ]; then
        fusermount -uz /mnt/disk1
    fi

    if [ $1 = "tmp" ]; then
        fusermount -uz $uroot/$dir
    fi
fi

